version: '3.8'
services:
  db:
    image: mariadb:10.4
    restart: unless-stopped
    container_name: db
    ports:
      - "13306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: magento
      MYSQL_USER: dbadmin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  redis:
    image: redis:6.0.4-alpine
    restart: unless-stopped
    container_name: redis
    ports:
      - "16379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
  elasticsearch:
    image: bitnami/elasticsearch:7
    restart: unless-stopped
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch_data:/bitnami/elasticsearch
    healthcheck:
      test: curl -s http://elasticsearch:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
  web:
    image: jane3030/nginx7.4-magento-ce-2.4.4:1.0.1
    container_name: web
    ports:
      - "18080:80"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    environment:
      BASE_URL: http://localhost:18080
      DB_HOST: db
      DB_NAME: magento
      DB_USERNAME: dbadmin
      DB_PASSWORD: password
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin123
      STORE_SESSION: redis
      REDIS_HOST: redis
      ELASTIC_SEARCH_HOST: elasticsearch
      ELASTIC_SEARCH_PORT: 9200
    volumes:
      - ./../application/i18n:/var/www/html/app/i18n
      - ./../application/app/design/frontend/sourceberry:/var/www/html/app/design/frontend/sourceberry
      - ./../application/app/design/adminhtml/sourceberry:/var/www/html/app/design/adminhtml/sourceberry
      - ./../application/app/code/sourceberry:/var/www/html/app/code/sourceberry
    healthcheck:
      test: curl -s http://web:80 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50